server:
  port: 8081

spring:
  application:
    name: Spring Boot Admin Server
  boot:
    admin:
      client:
        instance:
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}
          prefer-ip: true
        url: http://localhost:8081
        username: admin
        password: admin
  security:
    user:
      name: admin
      password: admin

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'